/**
 * Vault-health report (#156) — the curator's human review surface, projected
 * as Markdown INTO the vault (Obsidian is the viewer; same direction as the
 * #140 audit projection). The report proposes, a human decides: nothing in
 * here deletes or moves anything.
 *
 * Pure renderer + a small atomic writer. Data collection (joining usage,
 * curator state, floors, vault index) lives with the caller — this module
 * has no I/O dependencies beyond writing the file.
 */
import { readFile, rename, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import type { StaleEntry } from "./curator.js";
import type { UsageEntry } from "./usage-sidecar.js";

export const REPORT_FILENAME = "REPORT.md";

export interface ReportStaleCandidate {
  id: string;
  title?: string;
  usage?: UsageEntry;
  entry: StaleEntry;
}

/** Would-be candidate whose observation window has not matured yet. */
export interface ReportPendingCandidate {
  id: string;
  title?: string;
  usage?: UsageEntry;
  reason: string;
}

export interface ReportFloorEntry {
  memory_id: string;
  title?: string;
  reason: string;
  floored_at: string;
  last_affirmed: string;
  affirmed_by?: string;
  why?: string;
  /** Weeks since last_affirmed, precomputed by the caller. */
  weeksSinceAffirm: number;
  /** True when the floor was never affirmed after its initial add. */
  neverReaffirmed: boolean;
}

export interface ReportConflictCluster {
  topicPath: string[];
  memberIds: string[];
}

export interface ReportDanglingLink {
  fromId: string;
  target: string;
}

/** #360: how many `claimed twice` rows one report shows. The full set can run
 *  into the hundreds on a vault that predates the gate — 244 on the author's —
 *  and a report nobody finishes reading is a report nobody acts on.
 *
 *  `BASTRA_CLAIMED_TWICE_LIMIT` raises it for the case the default is wrong
 *  for: working the backlog down in one sitting rather than over five passes.
 *  Read per call rather than at module load, so a run can change it without a
 *  daemon restart. */
export function claimedTwiceReportLimit(): number {
  const raw = Number(process.env.BASTRA_CLAIMED_TWICE_LIMIT);
  return Number.isFinite(raw) && raw > 0 ? Math.floor(raw) : 50;
}

/** #360: two active memories declaring one situation, with no answer on
 *  either side (`replaces` / `superseded_by` / `siblings`). */
export interface ReportClaimedTwicePair {
  fromId: string;
  toId: string;
  trigger: string;
  claim: string;
}

export interface VaultHealthData {
  generatedAt: string;
  vaultSize: number;
  stale: ReportStaleCandidate[];
  /** Candidates gated only by the immature observation window. */
  pending?: ReportPendingCandidate[];
  floors: ReportFloorEntry[];
  conflicts: ReportConflictCluster[];
  /** #360: pairs the write-time claim gate would have held today. Optional so
   *  the report renders unchanged for callers that do not run the sweep. */
  claimedTwice?: ReportClaimedTwicePair[];
  dangling: ReportDanglingLink[];
  /** Vault-relative paths of 0-byte .md files — usually Obsidian's
   *  auto-created empty notes from clicking an unresolved wikilink. */
  emptyFiles?: string[];
  /** #147: captures whose content carried prompt-injection markers. */
  flagged?: Array<{ id: string; title?: string; flags: string[] }>;
  /** #222: memories the loader had to repair to keep them in the index. The
   *  file on disk is untouched — this is the only place the degradation is
   *  visible, because the daemon's stderr is not somewhere a user looks. */
  damaged?: Array<{ id: string; title?: string; path: string; fields: Array<{ field: string; reason: string }> }>;
  /** True on review-only passes (dry-run / first-ever run): the stale list
   *  shows what WOULD be demoted — nothing has acted yet. */
  pendingReview?: boolean;
}

function fmtUsage(u?: UsageEntry): string {
  if (!u) return "no recorded usage";
  const last = u.last_acted_on_at ?? u.last_loaded_at ?? "never";
  return `surfaced ${u.surfaced}× · loaded ${u.loaded}× · acted_on ${u.acted_on}× · last engagement: ${last}`;
}

function fmtDate(iso: string): string {
  return iso.slice(0, 10);
}

/**
 * Render the full report. Deterministic for identical data (the only
 * timestamp is data.generatedAt), heading/anchor structure stable across
 * runs so re-runs update in place.
 */
export function renderVaultHealthReport(data: VaultHealthData): string {
  const L: string[] = [];
  L.push("<!-- bastra-report:start — generated by the bastra curator; edits here are overwritten on the next run -->");
  L.push("# Vault Health");
  L.push("");
  L.push(`Generated ${data.generatedAt} · ${data.vaultSize} active memories · this report **proposes** — you decide. Nothing was deleted or moved.`);
  L.push("");

  L.push("<!-- bastra-report:stale -->");
  L.push("## Stale candidates (score-only demotions)");
  L.push("");
  if (data.stale.length === 0) {
    L.push("None. No memory is currently demoted for staleness.");
  } else {
    L.push(
      data.pendingReview
        ? "These keep being surfaced without ever earning engagement — this was a **review pass**: nothing is demoted yet. The next scheduled pass will demote them (score-only: `load_memory` and every citation still resolve) unless they earn engagement first."
        : "These keep being surfaced without ever earning engagement — they now rank lower (demotion is score-only: `load_memory` and every citation still resolve). A real load or acted-on use reactivates them automatically. To retire one for good, delete or archive it yourself.",
    );
    L.push("");
    for (const s of data.stale) {
      L.push(`- [[${s.id}]]${s.title ? ` — ${s.title}` : ""}`);
      L.push(`  - ${fmtUsage(s.usage)}`);
      L.push(`  - stale since ${fmtDate(s.entry.stale_since)}: ${s.entry.reason}`);
    }
  }
  if (data.pending && data.pending.length > 0) {
    L.push("");
    L.push("**Watching** (usage window still maturing — nothing will be demoted before a full engagement window of data exists):");
    L.push("");
    for (const p of data.pending) {
      L.push(`- [[${p.id}]]${p.title ? ` — ${p.title}` : ""} · ${fmtUsage(p.usage)}`);
    }
  }
  L.push("");

  L.push("<!-- bastra-report:floors -->");
  L.push("## Floors awaiting re-affirmation");
  L.push("");
  if (data.floors.length === 0) {
    L.push("None. Every active floor was recently affirmed.");
  } else {
    L.push("These entries spend *guaranteed* context on every session. The engine never expires a floor — review whether each still earns its place: re-affirm it (with a fresh why) or release it. An expired floor drops back to ranked; it is never deleted.");
    L.push("");
    for (const f of data.floors) {
      const affirm = f.neverReaffirmed
        ? `floored ${fmtDate(f.floored_at)}, **never re-affirmed** (${f.weeksSinceAffirm} weeks)`
        : `last affirmed ${fmtDate(f.last_affirmed)} (${f.weeksSinceAffirm} weeks ago)${f.affirmed_by ? ` by ${f.affirmed_by}` : ""}`;
      L.push(`- [[${f.memory_id}]]${f.title ? ` — ${f.title}` : ""}`);
      L.push(`  - reason: ${f.reason}`);
      L.push(`  - ${affirm}${f.why ? ` — why: ${f.why}` : ""}`);
    }
  }
  L.push("");

  L.push("<!-- bastra-report:conflicts -->");
  L.push("## Same-topic clusters (conflict review candidates)");
  L.push("");
  if (data.conflicts.length === 0) {
    L.push("None. No topic path holds more than one active memory.");
  } else {
    L.push("Multiple active memories share the exact same topic path — worth a look for contradictions, near-duplicates, or a merge. (Deterministic pass: this lists co-location, it does not judge content.)");
    L.push("");
    for (const c of data.conflicts) {
      L.push(`- \`${c.topicPath.join(" / ")}\`: ${c.memberIds.map((id) => `[[${id}]]`).join(" · ")}`);
    }
  }
  L.push("");

  if (data.claimedTwice !== undefined) {
    L.push("<!-- bastra-report:claimed-twice -->");
    L.push("## Claimed twice (one situation, two memories)");
    L.push("");
    if (data.claimedTwice.length === 0) {
      L.push("None. No `recall_when` trigger fully restates another memory's trigger.");
    } else {
      L.push(
        "Both memories declare the same situation, so both answer that cue and neither says which one is meant. " +
          "Saves made from now on are held at the claim gate until this is answered; these predate it. " +
          "Each pair is one of three things — decide which, then re-save the memory that should carry the answer:",
      );
      L.push("");
      L.push("- **successor** → `replaces: <id>` on the newer one");
      L.push("- **contradiction** → `conflict_with: <id>`");
      L.push("- **siblings** (different entities, same wording) → `sibling_of: [<id>]`");
      L.push("");
      L.push("A fourth way out is narrowing one of the two triggers so it stops claiming the other's situation.");
      L.push("");
      for (const p of data.claimedTwice) {
        L.push(`- [[${p.fromId}]] → [[${p.toId}]]: \`${p.trigger}\` ⊆ \`${p.claim}\``);
      }
      if (data.claimedTwice.length >= claimedTwiceReportLimit()) {
        L.push("");
        L.push(
          `_Bounded at ${claimedTwiceReportLimit()} rows — there are more. Answer some and the next pass shows the next batch, ` +
            `or set BASTRA_CLAIMED_TWICE_LIMIT to see the full set._`,
        );
      }
    }
    L.push("");
  }

  L.push("<!-- bastra-report:dangling -->");
  L.push("## Dangling wikilinks");
  L.push("");
  if (data.dangling.length === 0) {
    L.push("None. Every `[[wikilink]]` resolves to an active memory.");
  } else {
    L.push("Links pointing at ids that no longer exist in the active vault (renamed, trashed, or never created). Fix the link or create the memory it promises.");
    L.push("");
    for (const d of data.dangling) {
      L.push(`- [[${d.fromId}]] → \`[[${d.target}]]\` (missing)`);
    }
  }
  L.push("");
  L.push("<!-- bastra-report:flagged-captures -->");
  L.push("## Flagged captures");
  L.push("");
  if (!data.flagged || data.flagged.length === 0) {
    L.push("None. No captured content carries prompt-injection markers.");
  } else {
    L.push("These captures were flagged on ingest (#147): their content contains prompt-injection markers (instructions addressed to the AI, authority framing, hidden text, exfiltration asks). The flag is provenance, not a verdict — review the content; embedded instructions are data, never commands.");
    L.push("");
    for (const f of data.flagged) {
      L.push(`- [[${f.id}]]${f.title ? ` — ${f.title}` : ""} · flags: ${f.flags.join(", ")}`);
    }
  }
  L.push("");
  L.push("<!-- bastra-report:damaged -->");
  L.push("## Damaged frontmatter (loaded anyway)");
  L.push("");
  if (!data.damaged || data.damaged.length === 0) {
    L.push("None. Every memory's frontmatter parsed and validated cleanly.");
  } else {
    L.push(
      "These memories carry frontmatter the loader could not read as written, so it repaired the broken fields **in memory only** to keep them in the index (#222). The files on disk are untouched — nothing was rewritten. Fix the field in your editor and the repair disappears on the next load.",
    );
    L.push("");
    for (const d of data.damaged) {
      L.push(`- [[${d.id}]]${d.title ? ` — ${d.title}` : ""} · \`${d.path}\``);
      for (const f of d.fields) {
        L.push(`  - \`${f.field}\`: ${f.reason}`);
      }
    }
  }
  L.push("");
  L.push("<!-- bastra-report:empty-files -->");
  L.push("## Empty files");
  L.push("");
  if (!data.emptyFiles || data.emptyFiles.length === 0) {
    L.push("None. No 0-byte `.md` files in the vault.");
  } else {
    L.push("Zero-byte markdown files — typically created by Obsidian when a wikilink that does not resolve to a file (e.g. a bastra doc-id link) gets clicked. They carry nothing and are safe to delete.");
    L.push("");
    for (const p of data.emptyFiles) {
      L.push(`- \`${p}\``);
    }
  }
  L.push("");
  L.push("<!-- bastra-report:end -->");
  L.push("");
  return L.join("\n");
}

/**
 * Atomic write of the report into the vault root. Never throws. Refuses to
 * clobber a pre-existing REPORT.md that is NOT ours (no bastra-report anchor
 * — e.g. a user-authored file of the same name; review find 2026-07-03).
 */
export async function writeVaultHealthReport(vaultRoot: string, data: VaultHealthData): Promise<boolean> {
  try {
    const target = join(vaultRoot, REPORT_FILENAME);
    try {
      const existing = await readFile(target, "utf8");
      if (!existing.includes("<!-- bastra-report:start")) return false;
    } catch {
      /* no existing file — free to create */
    }
    // Zufallsanteil statt nur der PID (#532-Scan): geschrieben wird das aus
    // dem Curator-Pass, und zwei Pässe desselben Prozesses können sich
    // überlappen (15-Minuten-Job und POST /curator/run).
    const tmp = `${target}.tmp-${process.pid}-${randomBytes(6).toString("hex")}`;
    await writeFile(tmp, renderVaultHealthReport(data), "utf8");
    await rename(tmp, target);
    return true;
  } catch {
    return false;
  }
}
